# errno.h messages, also some Windows messages

0=Operation completed successfully.
1=Operation failed.
2=The system cannot find the file specified.
3=The system cannot find the path specified.
5=Access is denied.
6=The handle is invalid.
7=The storage control blocks were destroyed.
8=Not enough memory resources are available to process this command.
9=The storage control block address is invalid.
11=Try again.
13=Permission denied.
11=Try again 
12=Out of memory 
13=Permission denied 
14=Bad address 
15=Block device required 
16=Device or resource busy 
17=File exists 
18=Cross-device link 
19=No such device 
20=Not a directory 
21=Is a directory 
22=Invalid argument 
23=File table overflow 
24=Too many open files 
25=Not a typewriter 
26=Text file busy 
27=File too large 
28=No space left on device 
29=Illegal seek 
30=Read-only file system 
31=Too many links 
32=Broken pipe 
33=Math argument out of domain of func 
34=Math result not representable 
35=The disk is full.

# HTML codes
200=OK.
301=Moved permanently
302=Redirect.
403=Forbidden.
404=Access is denied.
405=Method not allowed.


# CMD code
9009=Command not found.

-1073741571=Segmentation fault